### PR TITLE
Added another user default group, i2c

### PR DESCRIPTION
**Pull request by radujipa**
Related to https://github.com/KanoComputing/peldins/issues/2146

### CODE REVIEW

**Comment by convolu** [comment]
Would you mind accompanying this with a small version bump? There hasn't been one in a while.

Also if possible update the date of license file at the top of the file to `2015-2016`, and `GPL v2`.
 Other than this it looks ok to me. :shipit:

**Comment by radujipa** [comment]
Sure thing! About the license, should we do this for all our repos (at some point) or just the files we touch for now?

**Comment by convolu** [comment]
Currently we only update the ones that we touch

**Comment by tombettany** [comment]
:+1:

**Pull request merged**
