### PR TITLE
Fixes for username and cached password issues

### PR DESCRIPTION
**Pull request by skarbat**
* Fixed login page username where it was displayed as "None"
 * Fixed the password on the same login window from being cached
 * Granted permissions to switch to virtual terminals from the Greeter

### CODE REVIEW

**Comment by alex5imon** [comment]
@skarbat why is this? `# FIXME: Cannot assign NLS token mark to literals below`

cc @tombettany

**Comment by skarbat** [comment]
@alex5imon I commented on the ticket, I get a run time error if I try to localize these strings, I have no idea why, perhaps Tom can help here.

**Comment by tombettany** [comment]
@skarbat What is an `NLS token mark`?

**Comment by skarbat** [comment]
@tombettany as in for example, `Header(_'title', _'description')` . Those underscores give me an exception if used in variable assignment. There was a long discussion a while ago as these tokens mean something else me thinks?

**Comment by skarbat** [comment]
@tombettany thanks! It was a simple typo from my side. works well now! cc @alex5imon

**Comment by tombettany** [comment]
Nice :)

**Comment by alex5imon** [comment]
Please merge :+1:

**Pull request merged**
