### PR TITLE
I18n gettext hooks for kano-greeter

### PR DESCRIPTION
**Pull request by hzulla**
This adds translation hooks to the `kano-greeter` python code.

kano-greeter

(Still not building my own packages, so I didn't test if the change in `setup.py` will tell distutils to correctly install the locale file, sorry. Please test this.)

### CODE REVIEW

**Comment by tombettany** [comment]
@hzulla Great work here by the way. Is it okay if we get the recipe for translation perfect with [Kano Updater](https://github.com/KanoComputing/kano-updater/pull/63) before we review all the PRs for the other great work that you've been doing on the translations? That can be our template and then all the refinements can trickle down to these ones.

**Comment by hzulla** [comment]
of course! I'll get back to working on Kano Updater.

**Comment by hzulla** [comment]
@tombettany ok, we're done with Kano Updater. Continue here or with Kano Settings?

**Comment by tombettany** [comment]
@hzulla Here is good. I think you just need to do what was done in https://github.com/KanoComputing/kano-updater/commit/0f0e550823293882e14853a04336ed409af00ac8:

 - Add package metadata to https://github.com/hzulla/kano-greeter/blob/411ffdf70c257b2abc509663caadadbef84e72d3/po/de.po#L1-L9
 - Add package name and copyright holder to https://github.com/hzulla/kano-greeter/blob/411ffdf70c257b2abc509663caadadbef84e72d3/po/Makefile#L19
 
Fix merge conflict:

```python
kano_greeter/user_list.py
<<<<<<< HEAD
        add_account_btn = OrangeButton('Add Account')
        add_account_btn.connect('clicked', self.add_account)
=======
        add_account_btn = OrangeButton(_('Add Account'))
        add_account_btn.connect('button-release-event', self.add_account)
>>>>>>> hzulla/i18n-gettext

kano_greeter/password_view.py
<<<<<<< HEAD
        self.login_btn = KanoButton('LOGIN')
        self.login_btn.connect('clicked', self._login_cb)
        self.attach(self.login_btn, 0, 3, 1, 1)

        delete_account_btn = OrangeButton('Remove Account')
        delete_account_btn.connect('clicked', self.delete_user)
        self.attach(delete_account_btn, 0, 4, 1, 1)
=======
        self.login_btn = KanoButton(_('Login').upper())
        self.login_btn.connect('button-release-event', self._login_cb)
        self.attach(self.login_btn, 0, 2, 1, 1)

        delete_account_btn = OrangeButton(_('Remove Account'))
        delete_account_btn.connect('button-release-event', self.delete_user)
        self.attach(delete_account_btn, 0, 3, 1, 1)
>>>>>>> hzulla/i18n-gettext
```

Anything else?

**Comment by hzulla** [comment]
Here you go.

Please do test the install line in `setup.py` as I'm not familiar with distutils. Thanks!

**Comment by tombettany** [comment]
There is a problem with the `setup.py` install which causes the `.mo` files to be installed directly into `/usr/share/locale` rather than into the language-specific subdirectory. [This patch](https://github.com/KanoComputing/kano-greeter/commit/b43fd3b620a572e0ade2675932ce220894d4ba34.patch) addresses the issue and builds correctly on our servers.

**Comment by hzulla** [comment]
Ok, thanks.

**Comment by tombettany** [comment]
I think this is ready to merge now. Anyone any objections?

**Comment by alex5imon** [comment]
Please merge :+1:

**Comment by hzulla** [comment]
Thanks!

**Pull request merged**
